// Edit any text here. Save, commit, push — the page updates.
window.CONTENT = {
  "name": "EVAN EMERY",
  "title": "SELECTED WORKS",
  "subtitle": "Human × Machine · Nine works · 2024 — 2025",
  "location": "Phoenix, Arizona",
  "instagram": "@evanemerydesign",
  "instagram_url": "https://www.instagram.com/evanemerydesign/",
  "email": "evanemerydesign@gmail.com",
  "linkedin": "evan-emery-2021",
  "linkedin_url": "https://www.linkedin.com/in/evan-emery-2021/",
  "statement_tagline": "I apply the machine as a means to express form.",
  "statement": [],
  "about_tagline": "",
  "about": [],
  "process_tagline": "",
  "process": [],
  "process_note": "Press play · 90 seconds · sound on",
  "works_label": "Nine works · 2024 — 2025 · all available",
  "insitu_label": "Framed and on the wall",
  "hide_thesis": true,
  "toggle_art": "Artwork",
  "toggle_ctx": "In situ",
  "list_label": "Retail prices · framed originals and prints",
  "footer_left": "Evan Emery · Phoenix, Arizona",
  "footer_right": "Selected works · 2024 — 2025",
  "works": [
    {
      "id": "duality",
      "title": "Duality",
      "year": "2025",
      "medium": "White ink on mat board",
      "size": "30 × 40 in",
      "price": "$1,800",
      "tools": "Rhino · Grasshopper",
      "output": "CNC pen plotter",
      "wide": true,
      "photo": false,
      "description": "",
      "context": "img/ctx-duality.jpg",
      "context_caption": "Duality, framed"
    },
    {
      "id": "deep-blue",
      "title": "Deep Blue",
      "year": "2025",
      "medium": "Cyanotype print on watercolor paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Octane Render · Vectron · C4D",
      "output": "Cyanotype",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "img/ctx-deep-blue.jpg",
      "context_caption": "Deep Blue, framed"
    },
    {
      "id": "distant-blues",
      "title": "Distant Blues",
      "year": "2025",
      "medium": "Cyanotype print on watercolor paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Octane Render · Vectron · C4D",
      "output": "Cyanotype",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "img/ctx-distant-blues.jpg",
      "context_caption": "Distant Blues, framed"
    },
    {
      "id": "fractal-blues",
      "title": "Fractal Blues",
      "year": "2025",
      "medium": "Cyanotype print on watercolor paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Octane Render · Vectron · C4D",
      "output": "Cyanotype",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "",
      "context_caption": ""
    },
    {
      "id": "falling",
      "title": "Falling",
      "year": "2025",
      "medium": "Cyanotype print on watercolor paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Octane Render · Vectron · C4D",
      "output": "Cyanotype",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "",
      "context_caption": ""
    },
    {
      "id": "dazzle-dim",
      "title": "Dazzle Dim",
      "year": "2024",
      "medium": "Archival pigment on fine art paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Rhino · Grasshopper",
      "output": "CNC pen plotter",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "img/ctx-dazzle-dim.jpg",
      "context_caption": "Dazzle Dim, framed"
    },
    {
      "id": "fracture-head",
      "title": "Fracture Head",
      "year": "2024",
      "medium": "Mixed media on fine art paper",
      "size": "25 × 31 in",
      "price": "$1,000",
      "tools": "Rhino · Grasshopper · Blender · DrawingBot v3",
      "output": "Spray paint · CNC pen plotter",
      "wide": false,
      "photo": false,
      "description": "",
      "context": "img/ctx-fracture-head.jpg",
      "context_caption": "Fracture Head, framed"
    },
    {
      "id": "disassembly",
      "title": "Disassembly",
      "year": "2025",
      "medium": "Ink on graph paper",
      "size": "18 × 22 in",
      "price": "$1,000",
      "tools": "Rhino · Grasshopper · DrawingBot v3",
      "output": "CNC pen plotter",
      "wide": false,
      "photo": true,
      "description": "",
      "context": "",
      "context_caption": ""
    },
    {
      "id": "dazzle-mass",
      "title": "Dazzle Mass",
      "year": "2025",
      "medium": "Archival pigment on fine art paper",
      "size": "18 × 22 in",
      "price": "$1,000",
      "tools": "Rhino · Grasshopper · Blender",
      "output": "Archival inkjet",
      "wide": false,
      "photo": true,
      "description": "",
      "context": "",
      "context_caption": ""
    }
  ]
};
